Feature/maintenance
DutchCodingCompany/read_more_less pull request #1
Opened 2023-03-28 12:34 UTC by Bassiuz

add tests and linting

2023-03-28 15:24 UTC, Guldem requested changes

2023-03-28 15:24 UTC, Guldem commented on analysis_options.yaml
> +    - lib/**/*.config.dart
Not sure if it makes sense to exclude generated files since we don't use code generation in this package.

2023-03-28 15:24 UTC, Guldem commented on example/test/read_more_less_test.dart
Shouldn't we relocate the tests to `test/` this is located in `example/test/`

2023-03-28 15:24 UTC, Guldem commented on lib/src/expandable_text.dart
> +        AnimatedCrossFade(
If the animation changes. Would be nice to update the example gif in the readme.

2023-03-28 15:24 UTC, Guldem commented on lib/src/expandable_text.dart
> +              style: widget.textStyle ?? Theme.of(context).textTheme.titleMedium,
Is it preferable to have a default textTheme specified?

2023-03-29 07:41 UTC, Bassiuz commented on lib/src/expandable_text.dart
>                    label: widget.iconExpanded ??
Seems like a nice next 'feature' to pick up; do you mind if I do that in a next pr?

2023-03-29 07:47 UTC, Bassiuz commented on lib/src/expandable_text.dart
> +              style: widget.textStyle ?? Theme.of(context).textTheme.titleMedium,
I moved it up a level because I needed the 'default' textstyle in calculating the amount of lines as well

2023-04-04 05:41 UTC, Guldem requested changes

2023-04-04 05:41 UTC, Guldem commented on lib/src/read_more_less.dart
> +          'You cannot custom icons while using a custom button builder',
Missing some words?

2023-04-04 05:43 UTC, Guldem approved these changes

2023-04-04 05:43 UTC, Guldem commented
One small thing left but the rest is LGTM!

2023-04-04 09:22 UTC, merged